### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [mknee123/jammming#3]
The project ran as intended. Great attention to detail. No major errors were detected. Since the only minor error were in relation to component lifecycle, state and props, here is a great document to review;

https://reactjs.org/docs/faq-state.html

In order to find out the best way to make your app run in a spefic order, refer to this document;
https://hackernoon.com/reactjs-component-lifecycle-methods-a-deep-dive-38275d9d13c0

**Comment by mknee123** [comment]
Thank you!
