### ISSUE TITLE
Updating state using HTML5 audio controls

### ISSUE THREAD

**Issue by zannain** [mknee123/jammming#6]
To actually play the track check out the [HTML Audio/Video](https://www.w3schools.com/tags/ref_av_dom.asp) element tags that have a fairly rich set of controls built into them that you can use to play the audio tracks. Check out this tutorial for a bit more advanced topic using [Javascript Web Audio API](https://robots.thoughtbot.com/javascript-audio-api). You can use these control to update state. Remember that when an event listener fires, all information about the current state is sent to the eventHandler, you can use this information to update the current `playState` of the track.  Here is a [tutorial](https://www.creativebloq.com/how-to/build-a-simple-music-player-with-react) that can get you started on some of the logic you will need

**Comment by mknee123** [comment]
Thank you. (:
